### PR TITLE
Some minor changes to set_taxonomicCovergae

### PR DESCRIPTION
**Pull request by liuanna**
modify set_taxonomicCoverage to handle a data.frame with multiple rows (species). Previous one assumes that the input data frame only has one row (species).

### CODE REVIEW

**Comment by mbjones** [comment]
Thanks @liuanna -- that looks like a great improvement.  In reviewing this, I notice that the method hard codes the ranks that the function can detect, which might prove problematic:
```R
taxon_classification = list("Kingdom","Phylum","Class","Order","Family","Genus","Species","Common")
```
In other EML work, we've found that many groups use other ranks, such as `Division`, 'Subfamily`, 'Tribe', 'Subtribe', and 'Variation', among many others.  I think the best approach would be to have the column names of the data frame correspond to the ranks desired, so that one person might provide:

Class | Genus | Species
------|------|-------
Mammalia|Ursus|arctos

and another might provide:

Class|Order|Suborder|Genus|Species|Subspecies
------|------|-------|-----|-----|-----
Mammalia|Carnivora|Caniformia|Ursus|arctos|horribilis
Mammalia|Carnivora|Caniformia|Ursus|arctos|gyas
```
How does that sound to you @cboettig ?

**Comment by liuanna** [comment]
Thank you @mbjones for pointing out. I think your approach is probably a better one, and we need to notify users to provide rank names in correct order. I was struggling on the order of rank names before. Since there is a large range of rank names and EML requires taxonomic coverage has a correct order (high to low), so my previous idea was to limit rank names to a certain number of rank names in correct order. However, definitely, some information are missing. 

I will update my codes. 

Thank you

**Comment by cboettig** [comment]
@liuanna Yup, having the user provide any rank names they so chose as column names and letting the function assume the rank names are in descending order makes sense to me too.

**Comment by mbjones** [comment]
Looks good, @liuanna -- I looked it over and tried the code, and it worked for me, and the coverage tests pass, so merging ...  Thanks for the code.  I'm sure we'll use this right away!

**Pull request merged**
