### PR TITLE
Fix up get_TextType

### PR DESCRIPTION
**Pull request by amoeba**
This PR addresses and closes two Issues with `get_TextType`

https://github.com/ropensci/EML/issues/229
https://github.com/ropensci/EML/issues/230

`get_TextType` should work nicely now with simple and complex cases.

### CODE REVIEW

**Comment by cboettig** [comment]
Good catch, thanks for the fix. Guess it would help if I wrote more complete unit tests (or finished writing my functions).  

These look good to me.  Can you add a note in NEWS.md to help us keep track of the changes? (probably some other PRs no listed there, but guess we can check back through the issues log before the next release).

**Comment by amoeba** [comment]
Done! I looked over the diff between what's on CRAN and master,

https://github.com/ropensci/EML/compare/v1.0.3...master

and see a few small things. I'll add notes about in another commit here.

**Comment by amoeba** [comment]
Okay, double done. I think I caught everything but more eyes the better.

**Comment by cboettig** [comment]
Thanks, LGTM!

**Pull request merged**
