### PR TITLE
Add support for converting EML into JSON-LD (via Schema.org/Dataset)

### PR DESCRIPTION
**Pull request by amoeba**
This isn't feature complete but covers the basic stuff for now.

I'd still like to:

- Test this more to make sure it doesn't produce incorrect JSON-LD or cryptic errors
- Agree on which Schema.org concepts to cover
- Find a way to get contact info into the markup

### CODE REVIEW

**Comment by cboettig** [comment]
Very cool!

Re testing the JSON-LD, might be good to add the rather nice `jsonld` R package to Suggests and add some tests.  For instance, a good test is that a round-trip expansion / compaction gets you back to where you started (modulo node order), in particular, that all properties fully compact.  Failure to get types correct (e.g. treating URIs as `@value` instead of `@id` etc) usually show up here.  See our examples in codemeta: https://github.com/ropensci/codemetar/blob/master/R/codemeta_validate.R  (though `validation` is probably too strong a term).  

One of the Berkeley undergrads has been working with us to reverse engineer the JSON schema that Google uses for the `Dataset` class on Google's SDTT (since of course they don't publish it! ug!), might be nearing a useful functionality for us here: https://github.com/ropenscilabs/datasauce/pull/4

Re `contact`, did you see my note about the example in the Google documentation?  I know that's not a complete answer, but a good starting place at least.   


Re design & maintenance strategy here, I wonder: 

1) should we make this functionality in a separate package?  generally I think maintaining several smaller, related packages is easier than one big one.

2) (A bit more extreme): should we tool this as a direct mapping between the original XML representation of EML and the JSON-LD?  e.g. have the R commands just use XPATH queries from `xml2` rather than any of EML's S4 classes?  I think that would be more robust and at least as easy to code for someone like you who already knows the EML schema and XPATH pretty well.  The whole `@` S4 class stuff never feels quite right.  (R would like S4 methods to have proper accessors, and it still ends up assuming some knowledge of the schema; though auto-complete on valid slot names is kinda helpful).  You work with this stuff more than me -- what do you think?

**Comment by amoeba** [comment]
Hey, thanks for the super awesome and detailed response. I'll reply in-lined:

> Re testing the JSON-LD, might be good to add the rather nice jsonld R package

This sounds like solid advice.

> Re contact, did you see my note about the example in the Google documentation? I know that's not a complete answer, but a good starting place at least.

I did, just hadn't addressed it yet in this PR.

> Re design & maintenance strategy here, I wonder:
> should we make this functionality in a separate package?

That doesn't sound too crazy. On one hand, adding in features for JSON(-LD) is mixing concerns with EML & XML here a bit. Though with just one basic feature, this would be like a micro-package which is kinda awkward. Can you imagine this as a EML-JSONLD or perhaps {anymetadatastandard} ->JSON-LD package? Or something else altogether?

> 2. (A bit more extreme): 

I actually like this too. I could play with that as an implementation and see how it feels. XPath is super powerful so it might get us all the way there. 

However, I don't totally get the rationale. 

1. I'm not sure there is a direct mapping between the XML and Schema.org JSON-LD. For example, abstract. This is one of those things that I can't imagine until I've written the entire implementation so take that with a grain of salt.
2. This feature (EML->JSONLD) at current doesn't involve the package user beyond making them call the function. So *how* it's done, so long as it's correct, doesn't bother me too much. Are you thinking about exposing some extra functionality that would make the user deal with either slots or XPaths?

Overall, I lean toward an EML XML -> Schema.org JSON-LD over an EML S4 -> Schema.org JSON-LD approach here.

**Comment by cboettig** [comment]
Sounds good.  

- re: micopackages, I'm all for them, if only to make my life easier.  Smaller code-bases are easier to maintain, even if a user would never need the functionality outside of the parent package: you see this happening in lots of RStudio packages.  Modularity is good, no package is too small (since easy to wrap in a metapackage), but many are too large.  (e.g. compare to `devtools` functionality being broken up behind-the-scenes into the `use_this` etc; but most users will never even notice).

- Re the motivation for using pure xpath calls rather than the `EML` R package's S4 classes: I agree that it makes no difference at all to the user; I'm thinking about our maintenance burden here as well.  The Xpath might be easier for us to write and extend, and makes the implementation robust to any changes we make in the EML package (not that I see us throwing out the S4 mechanism, if only for backwards compatibility -- but I could imagine an EML2 (really EML3) package that avoided it entirely).  There shoudn't be any difference between using `geographicCoverage@boundingCoordinates@southBoundingCoordinate` and `/geographicCoverage/boundingCoordinates/southBoundingCoordinate`, but having the mapping in XPath might help with some edge cases and also make it clear how to replace the R code with a pure  XSLT transform(?), which could be called from any language.  


-> EML-JSONLD or any->JSON-LD:  

Just for clarity, we want to remember there's really two things going on:  mapping between the EML namespace and the Schema.org namespace, and mapping between the XML serialization and the JSON serialization.  

> Can you imagine this as a EML-JSONLD or perhaps {anymetadatastandard} ->JSON-LD package?

Good question, though I think you mean "schema.org" instead of JSON-LD?   From an EML-centric point of view, it would be nicest I think to just have an XSLT sheet to transform into schema.org (in JSON), just as we have to go to other (XML-based) namespaces.  I think that's possible, but not sure,  I know very little XSLT.  

Alternately, we could imagine an EML-JSON-LD representation; still entirely in the EML namespace with no schema-org terms.  (There's various tools to automate this; like badgerfish, but these are clunky due to how much richer XML is than JSON.  Still, it probably wouldn't be too hard to conceptualize this in a way that can round-trip without loss, particularly given the light use of attributes in EML).  I think this would be an interesting exercise, but clearly different than what we have here.  (For comparison, the Open TreeOfLife project did exactly this to from the NeXML xml schema in to a json analog).  

This could be kinda cool; after a long time feeling like JSON was a somewhat pointless reinvention of XML without the associated tooling (XPath, XSD, XSLT, etc) I've come around to see something very developer-friendly in the simplicity, complemented by some equally powerful tooling (particularly the JSON-LD transforms).  It would probably be terrible for writing the next .docx format, but for expressing metadata I think this would be cool.  The LD part in particular also makes it much easier to make fully semantic (e.g. if one wants triple stores and SPARQL queries; I'm still on the fence about the value there), but I also easy to extend in a way that won't break existing tooling.

**Comment by amoeba** [comment]
Thanks for the feedback. I'm pretty down with switching to a dedicated package to support this feature and one that uses XPath instead of S4. I saw you created https://github.com/cboettig/emljson, is that for this purpose or something else?

**Comment by cboettig** [comment]
`emljson` is me brainstorming about my last comment there; doing an EML representation in pure JSON-LD (no schema.org involved).   I think this would be useful merely as another way to either create or consume EML. Probably should have left that for a separate thread; since it's essentially a tangent.

Originally I was thinking of that exercise as very different from the schema mapping exercise we started with in this thread.  Potentially one could go EML xml document -> `emljson` and then map that to `schema.org`, but I'm not sure there's anything particular to be gained by doing that vs just going straight from xml+EML into json-ld+schema.org via XPath.  

So, it would be great to forge ahead in a separate R package that could take EML xml and create a JSON-LD document using the Schema.org/Dataset namespace just by using XPath calls.   I'm happy to chip in; want to initiate a repo for this?

Separately, I'd love to have your help on `emljson` if that sounds interesting.  I think having EML in JSON-LD could be really compelling from both a user and developer point of view.

**Comment by amoeba** [comment]
Deal on both points. We have to have a cool name though and I'm horrible at names.

- `emlext`
- `emlextra`
- `emlexport`
- `emltoschemaorg`

Maybe I need a ☕️ and a 🍩. Happy to do that.

A note on the EML->JSON front, for our EML editor webapp, we're using a generic XML->JSON converter which works pretty well for just getting JSON for us to use in models and views.

**Comment by cboettig** [comment]
hmm, I'm no good at names either, but will ping if something hits me.

re generic xml->json converters: I find these don't always give very natural JSON though.   Does yours support the ability to round-trip?  I think the use cases for a lossy converter are less compelling; but full round-trip also means pretty ugly JSON.  (e.g. rules for repeated nodes, dealing with attributes, etc).  Certain things in XML are sure to be problematic -- e.g. think a textType block like: `<text>This is some <strong>emphasized</strong> text</text>`.  What does your generic converter do with that?  (I think the "right" thing is not to translate those strings)

Also, this raises some differences between JSON and JSON-LD, since not all mappings make semantic sense.  Remember that because JSON-LD is linked data, it has to make sense semantically -- and therefore should be robust to things like ordering of the attributes, nesting vs referencing by id, etc (remember it's all just triples in the end).  JSON-LD framing provides a good mechanism to get your data back in the desired nesting etc, but I think this will require creating a mapping manually with an eye to the actual semantics involved.  Not sure how much an 'automatic' converter would help.  (Analgously, in R one could do:  `read_xml() %>% as_list() %>% write_json()` and get EML -> JSON, but it's not pretty.  Even leaving JSON aside,  `read_xml() %>% as_list() %>% as_xml_document()` doesn't always round-trip!

**Comment by amoeba** [comment]
Yeah it's pretty messy. I don't know off-hand if ours does any of those things well.

**Pull request closed without merging**
