### PR TITLE
adds eml_view function 

### PR DESCRIPTION
**Pull request by masalmon**
Cf #189

### CODE REVIEW

**Comment by cboettig** [comment]
Nice, thanks! Can you add a quick unit test file for these, e.g. based on the examples you've already added?  Do you think it would be good to include one of these examples in the 'reading eml' vignette too, so people know it's there?

**Comment by masalmon** [comment]
yes x2 I will in the next days, I just wanted to be sure the new function was deemed useful first 😉

**Comment by masalmon** [comment]
I cannot have a test for when `listviewer` isn't installed which isn't perfect for coverage, but I don't think it can be helped?

**Comment by cboettig** [comment]
Thanks! Right, No worries, coverage isn't perfect anyway.

**Pull request merged**
