### PR TITLE
coercion of factors to data.frame

### PR DESCRIPTION
**Pull request by maelle**
I didn't add a test with my example because it'd mean adding `tibble` in Suggests, is it worth it?

### CODE REVIEW

**Comment by maelle** [comment]
See issue #204

**Comment by maelle** [comment]
I added a test for the case I describe in https://github.com/ropensci/EML/issues/159

**Comment by maelle** [comment]
So I've noticed something weird. With the first version of the modified test-validation.R the test failed when I sourced the file but not when doing `devtools::test()`. Now it does but because I saved test-validation.R with the latin1 encoding. I'm not sure it's a good idea but at least now it reproduces the issue I've been having when trying to test an EML I had just created without saving it first (somehow it seems more logical to me to first validate it and then save it).

**Comment by maelle** [comment]
Mmmh so now it works on my PC but nowhere else. I wonder if the solution will include using information from `Sys.info()['sysname']`

**Comment by maelle** [comment]
The error that's currently make the code fail on AppVeyor is a pandoc error that I don't get locally. :thinking:

**Comment by maelle** [comment]
Now I wonder if this is the only test using pandoc? Because the test fails at the `set_methods` stage, it doesn't fail later for the name with accent.

**Comment by maelle** [comment]
I'm sorry that this PR thread is getting so long. For installing pandoc on Appveyor I used Jenny's last comment in this [issue](https://github.com/krlmlr/r-appveyor/issues/82)

**Comment by cboettig** [comment]
Thanks for all the work on this.

Re: pandoc: Pandoc is called by the `set_TextType()` and `get_TextType()` functions, but I turned these tests off for Appveyor / windows because I couldn't get them to pass, not sure why (see Bug #179).

Re: external file in the vignette:  We should probably just put a copy of that file into `inst/examples` and read it in with `system.file` instead....

Re the encoding issues: these sound rough.  I do wonder if we can isolate to what extent the encoding issues we're hitting on windows have to do with `xml2` and `testthat` etc; it's not obvious that we're doing anything unexpected in EML, particularly given that the error is operating-system specific.  I don't feel great with a solution of writing a file on windows using the default (`UTF-8`) encoding and reading it back in with `latin1` encoding.  It would be great to isolate a minimal case of this error in pure `xml2` and maybe we can enlist the superpowers of @jimhester and co in figuring out what is going wrong on Windows validation.  I know encoding types on Windows have always been pretty complicated but don't have much first-hand experience.

**Pull request merged**
