### PR TITLE
Implement get_abstract and abstract part of get_TextType

### PR DESCRIPTION
**Pull request by amoeba**
As discussed in #194, we decided to implement a helper function called
get_abstract that would return a text representation of the EML
abstract. My first attempt involved copying most of the function body
of get_TextType into get_abstract so I refactored the two functions to
make use of a node_to_file helper method that does the conversion with
pandoc.

### CODE REVIEW

**Comment by amoeba** [comment]
I think I preserved the functionality of get_TextType. I changed some of the `file.copy` calls so I'd love it you could verify I didn't break any behavior I didn't understand.

**Comment by cboettig** [comment]
I'll take a look, but yeah, the path mess in the `file.copy` calls was mostly my vain attempt to make these functions windows-compatible.  For some reason they still fail on appveyor, you'll see the `get_TextType` tests use a lot of `skip_on_windows`.  Your guess is as good as mine there, debugging via appveyor isn't much fun & I don't have a local windows or windows emulator.

**Comment by amoeba** [comment]
Oh, jeez. I can take a look and test this out on Windows next week some time I bet.

**Comment by cboettig** [comment]
yeah, the basic logic is just to work in a tmp dir for the pandoc commands, since pandoc doesn't let the `to` or `from` file arguments include paths.  The rest of the nonsense with `file.path` and `normalizePath` are supposed to be R's way of making the path calls platform independent, but for some reason they still seem to cause problems.  Might be related to how `tmpdir` works in Windows too?  I dunno, see the thread #175

**Comment by cboettig** [comment]
I think the goal of returning a character string rather than a file is going to be applicable to really any `TextType` element, probably not just an abstract.  (e.g. think the various method description steps, etc).  So it would probably be best to move that behavior into a generic extractor (e.g. part of get_TextType?)  

In the S4 spirit discussed in #196, this might make more sense as a coercion, e.g. 

```r
eml <- read_eml(..)
abst <- abstract(eml)
as(abst, "character")

## or in other formats
as(abst, "html")
```

Thoughts?

**Comment by amoeba** [comment]
Oh, that's way cleaner. Maybe I can delete this PR and we can work on this later on. Sound good?

**Comment by cboettig** [comment]
sounds like a plan

**Pull request closed without merging**
