### PR TITLE
Couple of updates

### PR DESCRIPTION
**Pull request by amoeba**
See commit messages below...

### CODE REVIEW

**Comment by cboettig** [comment]
@amoeba sorry for slow reply.  a few checks look unhappy?

**Comment by amoeba** [comment]
Ah, right. CHECK is failing because the examples in `set_TextType` are broken. Need to fix those at some point I guess. Once those examples are removed, the test suite fails because I updated it to match our recent change in `emld` but testing uses the released version.

**Comment by cboettig** [comment]
thanks, okay cool, we should probably take care of the `emld` release (though I suppose we could add a `Remotes` to DESCRIPTION here to force it to use the dev version meanwhile, especially if this is effecting typical user functions and not just an issue for the test suite...)

Are we still thinking about `emld_version()` strategy?

**Comment by amoeba** [comment]
From https://github.com/ropensci/emld/issues/65 it sounds like we should get this merged. Sorry I hadn't gotten back to you on:

> Are we still thinking about emld_version() strategy?

I think what we have in place now is good enough, esp. good enough for a release.

**Comment by cboettig** [comment]
this merge breaks some of the `set_TextType` examples as noted above, which causes the checks to fail.  Are those examples out of date?  Maybe they can be dropped?

**Comment by amoeba** [comment]
Yeah, IIRC those coercions are out of date.

**Comment by cboettig** [comment]
ah, yeah, I see, we can just drop `as()` coercion, that's no longer needed as the set methods already return the right object.  I've dropped those now and things look good check-wise.  

Looks like NEWS.md hasn't been updated since last release -- wanna send a quick PR with any key changes we oughta mention?  Then I'll get this and `emld` updated on CRAN.

**Comment by amoeba** [comment]
Sure, on its way shortly.

**Pull request merged**
