### PR TITLE
set_taxonomicCoverage accepting arbitrary taxonomicClassification

### PR DESCRIPTION
**Pull request by liuanna**
* Make ```set_taxonomicCoverage``` accept character string, list, data frame of scientific names
* Revise ```get_taxonomicCoverage``` to have rank names as column names of returned data frame
* Document and export ```set_taxonomicCoverage```
* Add unit test

### CODE REVIEW

**Comment by cboettig** [comment]
Hi Anna,

Thanks,great work on this.  In the `data.frame` version, you seem to be listing the data as a single row, with ranks as the column names and values as the row.  

I think the table should instead have just two columns, one for rank, one for value, so that it resembles the output table from `get_taxanomicCoverage` (i.e. it should be easy to round-trip the output of `get_taxanomicCoverage` into a new `set_` function.  

It would be good to add a few more expectations to your tests -- ensure that the data is actually being added, not just that the object returned is of the correct class.  Ideally at least one of the unit tests should involve writing a minimal EML file that uses `set_coverage()` and validating it.  

Also, if I'm not mistaken, at present this representation only allows the full taxonomic coverage to be specified for a single species.  Ideally one could give the full classification for multiple species; though exactly how that should be structured is not entirely obvious to me.  @mbjones thoughts on this?

**Comment by liuanna** [comment]
Hi Carl @cboettig ,

Previously, I thought it would be convenient for users to list the data as a single row, with ranks as the column names and values as the row based on the format of taxon file of GDPP. So I also modified get_taxonomicCoverage to return data frame in this format. However, I am not sure if it is really convenient for users or how users usually construct data tables for taxonomic classification in real life. 

For the last part, I am kind of confused by what you mean by "full classification for multiple species"?
Do you mean something like this? For this example below, construct a taxonomicCoverage for each line?
Then return a list of taxonomicCoverage?


|CommonName            |TaxonomicPhylum |TaxonomicClass |TaxonomicOrder |TaxonomicFamily |TaxonomicGenus |
|:---------------------|:---------------|:--------------|:--------------|:---------------|:--------------|
|Hazel grouse          |Chordata        |Aves           |Galliformes    |Tetraonidae     |Bonasa         |
|Anole lizard          |Chordata        |Reptilia       |Squamata       |Iguanidae       |Anolis         |
|Blue-tailed damselfly |Arthropoda      |Insecta        |Odonata        |Coenagriidae    |Ischnura       |
|Common darter         |Arthropoda      |Insecta        |Odonata        |Libellulidae    |Sympetrum      |
|Four-spotted chaser   |Arthropoda      |Insecta        |Odonata        |Libellulidae    |Libellula      |
|Azure damselfly       |Arthropoda      |Insecta        |Odonata        |Coenagriidae    |Coenagrion     |

**Comment by cboettig** [comment]
I see, you my be right that this wide format is better.  In that case we probably should revise get_ method accordingly too (though I think your first version still wasn't returning the lower-evel ranks in my test?)

  One difficulty comes from the nested nature of the EML representation  -- what happens if a user puts the columns in a different order?  It is hard for the function to check for this automatically since unfortunately taxon ranks in EML are a freeform text field not a controlled vocabulary.  I guess it is OK as long as the documentation clearly states columns should be in order from higher to lower taxonomic rank.

**Comment by liuanna** [comment]
In my previous commit 0b296851c32b8c32e32713d0aa1d39e5d58c3934, I modified get_taxonomicCoverage. The code looks like below and works in the way the example shows. I think the function does dig into lower levels. 

```
get_taxonomicCoverage <- function(taxonomicCoverage){
  df <- lapply(taxonomicCoverage[[1]]@taxonomicClassification, taxa_to_df)[[1]]
  df <- t(as.data.frame(df))
  colnames(df) = df[1,]
  df = t(as.data.frame(df[-1,]))
  rownames(df) = NULL
  as.data.frame(df)
}

taxa_to_df <- function(object){
  df <- data.frame(rank = character(), value = character())
  while(length(object@taxonomicClassification) > 0){
    df <- rbind(df, data.frame(rank = object@taxonRankName,
                               value = object@taxonRankValue))
    object <- object@taxonomicClassification[[1]]
  }
  df <- rbind(df, data.frame(rank = object@taxonRankName,
                             value = object@taxonRankValue))
  df
}

# example
library(EML)
 f <- system.file("xsd/test/eml-i18n.xml", package="EML")
eml <- read_eml(f)
df <- get_taxonomicCoverage(eml@dataset@coverage@taxonomicCoverage)
df
```
|KINGDOM |PHYLUM     |CLASS        |ORDER        |FAMILY       |GENUS       |genusSpecies         |commonName |
|:-------|:----------|:------------|:------------|:------------|:-----------|:--------------------|:----------|
|Plantae |Phaeophyta |Phaeophyceae |Laminariales |Lessoniaceae |Macrocystis |Macrocystis pyrifera |MAPY       |

**Comment by liuanna** [comment]
Do you think it is possible that we specify a list of rank names in correct order and then we search for certain names in column names of data frame? Then produce the nested taxonomicClassfication in the order we specify? 
For example, we can specify ```list("Kingdom","Phylum","Class","Order","Family","Genus","genusSpecies","Common")```, then we look for these names in column names of data frame.  I am wondering if it is possible to list all potential rank name in correct order?

**Comment by cboettig** [comment]
hmm... might be possible, but taxon rank names vary a lot (and not just in the use of various 'sub-' prefixes).  That's probably why EML didn't just restrict authors to a set of 8 or so rank names to begin with (@mbjones might be able to clarify that when he gets back).  

For now I think we're best for now just adding a note in the function documentation about the order to list ranks.

Can you update the PR to use this wide format for both `get_` and `set_` methods, including updating the examples in the roxygen and the `testthat` tests?  I think the `testthat` tests still need also at least one call that includes checking a minimal document against `eml_validate`.  Then we can go ahead and merge.  Thanks for your good ideas and good work on this one!

**Comment by cboettig** [comment]
@liuanna Thanks!  But looks like the automated travis checks are failing now -- can you take a look and fix?

**Comment by liuanna** [comment]
okay, let me look into it.

**Comment by liuanna** [comment]
@cboettig Carl, after I commented out the test function that checking if set_taxonomicCoverage helps generate valid EML, all checks passed. The test functions passed in my local machine and eml_validate indeed returns TRUE. However, if I include ```testthat::expect_true(eml_validate(eml))```, error occurs and tests failed.

**Comment by cboettig** [comment]
Great!  Instead of commenting out that test, can you use `skip_on_travis()` & `skip_on_cran()` (see testthat manual or the r pkg book) to skip that one?  Nearly ready!

**Comment by cboettig** [comment]
Very nice! Merged.

**Comment by liuanna** [comment]
Thank you!

**Pull request merged**
