### PR TITLE
Fix #189 issue (listviewer function commented out)

### LINKED ISSUE #189: viewing EML interactively (e.g. via htmlwidget / listviewer)
I don't know whether it's worth mentioning in the doc somewhere but using `jsonedit` from the [`listviewer` package](https://github.com/timelyportfolio/listviewer) for looking at the xml is quite handy IMO (after transforming the eml to a list)

### PR DESCRIPTION
**Pull request by cboettig**
We'll see if this passes checks!

### CODE REVIEW

**Comment by cboettig** [comment]
@maelle @amoeba No such luck.  Looks like the listview function is throwing an error on all platforms now (see CI report above).   No idea why, seems to be deep in the internals of the `print.htmlwidget()` function and not something directly part of the EML code.    Thoughts?

**Comment by maelle** [comment]
What about switching from `listviewer` to https://github.com/hrbrmstr/xmlview then? :thinking:

**Comment by cboettig** [comment]
Looks very promising!

**Comment by maelle** [comment]
will try to make the change at some point next week, fingers crossed

**Comment by maelle** [comment]
`xmlview` is not on CRAN though

**Comment by maelle** [comment]
I think it's due to some elements of the EML that are unnamed because I get the same error using `xmlview`. Currently investigating.

**Comment by cboettig** [comment]
closing in favor of #223

**Pull request closed without merging**
