### PR TITLE
Add an initial set of party and related helper functions

### PR DESCRIPTION
**Pull request by amoeba**
Here's an initial set of party helpers which I think is comprehensive of the party module. I consider this PR incomplete as I'd like to still:

- Do a pass over the existing code base, docs, and vignettes to see if these changes necessitate changes in other places (e.g., update a vignette or two)
- Get your feedback on how I went about this:
    - Do we like the function names? e.g., `set_creator` could be called `eml_creator` or `creator`
    - Do we want to make these functions to more error checking? They assume sane inputs
    - Do we like how I went about writing roxygen docs? Specifically prepending the `(class)` to each `@param` and showing that multiple types can be passed with `(type1|type2)`
- Improve the examples so each helper function has examples that cover its full abilities

### CODE REVIEW

**Comment by cboettig** [comment]
> Do we like the function names? e.g., `set_creator` could be called `eml_creator` or `creator`

Current pattern uses `set_*` for other similar high-level functions, so I think we should keep it.  (also seems needless to break an API you are already using based on your original implementation).  `creator` would be the proper S4 constructor way, but we don't really have full S4 accessor / initializer methods anyway.

> Do we want to make these functions to more error checking? They assume sane inputs

Looks fine to me.  Checks are nice of course, but this looks reasonable an consistent with other `set_*` methods, which do no or minimal checks.  Like we discussed on Slack, I think the better solution long-term in a rewrite would automate more things so fewer checks are necessary (even at the cost of making it impossible to create certain more arcane EML constructions)

> Do we like how I went about writing roxygen docs? Specifically prepending the (class) to each @param and showing that multiple types can be passed with (type1|type2)

yup, LGTM

**Comment by amoeba** [comment]
Okay, I did a quality/sanity check and finished up roxygen docs for each function. I feel like this is good to merge.

**Comment by amoeba** [comment]
Fixing r cmd check issues now.

**Comment by amoeba** [comment]
Okay, r cmd check issues fixed, a few unit and regression tests added for fun. I don't think r cmd check will fail on appveyor or travis. Let me know if you have any thoughts or concerns and, if not, please merge away!

**Pull request merged**
